; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:giga_r1_m7]
platform = ststm32 
board = giga_r1_m7
framework = arduino
build_flags =
	-DSDA=9
	-DSCL=8
lib_deps = 
    arduino-libraries/Arduino_GigaDisplay_GFX@^1.1.0
    arduino-libraries/Arduino_GigaDisplayTouch@^1.0.1
    dfrobot/DFRobot_GP8XXX@^1.1.0
    adafruit/Adafruit ADS1X15@^2.6.2